/* APIs */
export const FIND_STOCK_SYMBOL_SUCCESS = "FIND_STOCK_SYMBOL_SUCCESS";
export const QUOTE_SYMBOL_SUCCESS = "QUOTE_SYMBOL_SUCCESS";
export const COMPANY_INFO_SUCCESS = "COMPANY_INFO_SUCCESS";
export const CHART_INFO_SUCCESS = "CHART_INFO_SUCCESS";
export const STOCK_NEWS_SUCCESS = "STOCK_NEWS_SUCCESS";
export const MARKET_NEWS_SUCCESS = "MARKET_NEWS_SUCCESS";

/* MySQL */
export const GET_STOCKS_SUCCESS = "GET_STOCKS_SUCCESS";
export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS";
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";

/* Other */
export const STOCK_NAME_SUCCESS = "STOCK_NAME_SUCCESS";
export const STOCK_TIMING_SUCCESS = "STOCK_TIMING_SUCCESS";