export const GET_STOCKS_SUCCESS = "GET_STOCKS_SUCCESS";
export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS";
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";